set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'tmux-plugins/tmux-sensible'

#unbind C-b
#set-option -g prefix C-a
#bind-key C-a send-prefix
#set -g status-style 'bg=#333333 fg=#5eacd3'

#bind r source-file ~/.tmux.conf
set -g base-index 1

#bind -T copy-mode-vi v send-keys -X begin-selection
#set -s set-clipboard on

#bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

#set-option -g history-limit 10000
#set-option -g focus-events on
#set-option -sa terminal-overrides alacritty:RGB
# vim-like pane switching
#bind -r ^ last-window
#bind -r k select-pane -U
#bind -r j select-pane -D
#bind -r h select-pane -L
#bind -r l select-pane -R

#bind -r D neww -c "#{pane_current_path}" "[[ -e TODO.md ]] && nvim TODO.md || nvim ~/Documents/todo.md"

#set -g allow-rename on
#set -g renumber-windows on
#set -g default-terminal "${TERM}"
#set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
#set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'
#set -g focus-events on
set -g mouse on


# forget the find window.  That is for chumps
#bind-key -r f run-shell "tmux neww ~/.local/bin/tmux-sessionizer"

#bind-key -r i run-shell "tmux neww tmux-cht.sh"
#bind-key -r J run-shell "~/.local/bin/tmux-sessionizer ~/src/gitlab-master.nvidia.com/carbide"
#bind-key -r C run-shell "~/.local/bin/tmux-sessionizer ~/work/tvui"
#bind-key -r R run-shell "~/.local/bin/tmux-sessionizer ~/work/milo"
# bind-key -r L run-shell "~/.local/bin/tmux-sessionizer ~/work/hpack"
#bind-key -r H run-shell "~/.local/bin/tmux-sessionizer ~/personal/vim-with-me"
#bind-key -r T run-shell "~/.local/bin/tmux-sessionizer ~/personal/refactoring.nvim"
#bind-key -r N run-shell "~/.local/bin/tmux-sessionizer ~/personal/harpoon"
#bind-key -r S run-shell "~/.local/bin/tmux-sessionizer ~/personal/developer-productivity"
# Reload the tmux conf file; this is useful when we edit as we go.
bind r source-file ~/.tmux.conf \; display 'Config reloaded'

#source-file 'tmux/base16-catppuccin-mocha.conf'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin '27medkamal/tmux-session-wizard'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tinted-theming/base16-tmux'

set -g default-shell "$SHELL"

set -g @colors-base16 'catppuccin'
# Sane scrolling
# set -g terminal-overrides 'xterm*:smcup@:rmcup@'
#set -g terminal-overrides '\*:smcup@:rmcup@'

#set -g @session-wizard 'T'
#run-shell ~/.local/share/tmux/tmux-session-wizard/tmux-session-wizard.tmux

run '~/.tmux/plugins/tpm/tpm'
