[graphics.variables]
font_size = 12
font = "Hack Nerd Fonrt"

[i3]
depends = ["graphics"]

[i3.files]
i3 = "~/.config/i3"
i3status-rust = "~/.config/i3status-rust"
rofi = "~/.config/rofi"
dunst = "~/.config/dunst"

[zsh.files]
".zshrc" = "~/.zshrc"
".zsh" = "~/.zsh"
".antigenrc" = "~/.antigenrc"

[spotifyd.files]
spotifyd = "~/.config/spotifyd"

[Xresources.files]
".Xmodmap" = "~/.Xmodmap"
".Xresources" = "~/.Xresources"

[scripts.files]
"scripts/rofi-screenshot" = "~/.local/bin/rofi-screenshot"

[sheldon.files]
sheldon = "~/.config/sheldon"

[alacritty.files]
alacritty = { target = "~/.config/alacritty", type="symbolic"}

[tmux.files]
".tmux.conf" = "~/.tmux.conf"
