add_newline = false

[kubernetes]
style = "bg:#665c54"
format = "[$symbol$cluster( ($namespace))]($style) "
disabled = false

[kubernetes.context_aliases]
'dev.local.cluster.k8s'= 'dev'
'.*/openshift-cluster/.*'= 'openshift'
'gke_.*_(?P<var_cluster>[\w-]+)'='gke-$var_cluster'

[kubernetes.user_aliases]
"dev.local.cluster.k8s"= "dev"
"root/.*"="root"

[username]
format = "[$user@]($style)"
show_always = true
style_user = "bg:#458588"
style_root = "bg:#458588"

[fill]
symbol = " "
disabled = false

#[time]
#time_format = "%R"
#format = "[$time]($style)"
#disabled = false

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#504945"
format = '[  $time ]($style)'

[hostname]
format = "[@$hostname]($style) "
ssh_only = false
style = "bg:#928374"
#style = "bold green"


[directory]
style = "bg:#98971a"
format = "[ $path ]($style)"
truncation_length = 8
truncation_symbol = "…/"


[git_branch]
symbol = ""
style = "bg:#d79921"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#d79921"
format = '[$all_status$ahead_behind ]($style)'
