[theme]
theme = "ctp-mocha"

[icons]
icons = "awesome4"

[[block]]
block = "memory"

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"


[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %Y-%m-%d %H:%M:%S') "

#[[block]]
#block = "custom"
#command = "echo \uf030" # assumes fontawesome icons
#interval = "once"
#[[block.click]]
#button = "left"
#cmd = "sh ~/.local/bin/screenshot 2>/tmp/custom_block.log"
